"""UI microcopy translations (NFR11 i18n framework).

English is authoritative. French and Swahili are direct translations of short UI
labels (not medical content, so no clinical vetting is required). Arabic includes
`dir: rtl` metadata consumed by the frontend to flip layout direction.

Health-education *content* (medical articles) is a separate concern — see
HealthEducationArticle.is_verified, which tracks whether a qualified reviewer has
signed off on the medical accuracy of translated content, per the SRS business rule.
"""

LANGUAGES = ['en', 'fr', 'sw', 'ar']
RTL_LANGUAGES = ['ar']

LABELS = {
    'login': {'en': 'Login', 'fr': 'Connexion', 'sw': 'Ingia', 'ar': 'تسجيل الدخول'},
    'register': {'en': 'Register', 'fr': "S'inscrire", 'sw': 'Jisajili', 'ar': 'تسجيل'},
    'logout': {'en': 'Log out', 'fr': 'Déconnexion', 'sw': 'Toka', 'ar': 'تسجيل الخروج'},
    'dashboard': {'en': 'Dashboard', 'fr': 'Tableau de bord', 'sw': 'Dashibodi', 'ar': 'لوحة التحكم'},
    'appointments': {'en': 'Appointments', 'fr': 'Rendez-vous', 'sw': 'Miadi', 'ar': 'المواعيد'},
    'medical_records': {'en': 'Medical Records', 'fr': 'Dossiers médicaux', 'sw': 'Rekodi za Afya', 'ar': 'السجلات الطبية'},
    'health_education': {'en': 'Health Education', 'fr': 'Éducation à la santé', 'sw': 'Elimu ya Afya', 'ar': 'التثقيف الصحي'},
    'emergency': {'en': 'Emergency', 'fr': 'Urgence', 'sw': 'Dharura', 'ar': 'طوارئ'},
    'book_appointment': {'en': 'Book Appointment', 'fr': 'Prendre un rendez-vous', 'sw': 'Weka Miadi', 'ar': 'حجز موعد'},
    'new_appointment': {'en': '+ New appointment', 'fr': '+ Nouveau rendez-vous', 'sw': '+ Miadi mpya', 'ar': '+ موعد جديد'},
    'add_record': {'en': '+ Add record', 'fr': '+ Ajouter un dossier', 'sw': '+ Ongeza rekodi', 'ar': '+ إضافة سجل'},
    'full_name': {'en': 'Full name', 'fr': 'Nom complet', 'sw': 'Jina kamili', 'ar': 'الاسم الكامل'},
    'phone_number': {'en': 'Phone number', 'fr': 'Numéro de téléphone', 'sw': 'Nambari ya simu', 'ar': 'رقم الهاتف'},
    'password': {'en': 'Password', 'fr': 'Mot de passe', 'sw': 'Nenosiri', 'ar': 'كلمة المرور'},
    'age': {'en': 'Age', 'fr': 'Âge', 'sw': 'Umri', 'ar': 'العمر'},
    'gender': {'en': 'Gender', 'fr': 'Genre', 'sw': 'Jinsia', 'ar': 'الجنس'},
    'country': {'en': 'Country', 'fr': 'Pays', 'sw': 'Nchi', 'ar': 'الدولة'},
    'region': {'en': 'Region', 'fr': 'Région', 'sw': 'Mkoa', 'ar': 'المنطقة'},
    'submit': {'en': 'Submit', 'fr': 'Soumettre', 'sw': 'Wasilisha', 'ar': 'إرسال'},
    'cancel': {'en': 'Cancel', 'fr': 'Annuler', 'sw': 'Ghairi', 'ar': 'إلغاء'},
    'save': {'en': 'Save', 'fr': 'Enregistrer', 'sw': 'Hifadhi', 'ar': 'حفظ'},
    'loading': {'en': 'Loading...', 'fr': 'Chargement...', 'sw': 'Inapakia...', 'ar': 'جارٍ التحميل...'},
    'welcome': {'en': 'Welcome', 'fr': 'Bienvenue', 'sw': 'Karibu', 'ar': 'مرحباً'},
    'profile': {'en': 'Profile', 'fr': 'Profil', 'sw': 'Wasifu', 'ar': 'الملف الشخصي'},
    'edit_profile': {'en': 'Edit profile', 'fr': 'Modifier le profil', 'sw': 'Hariri wasifu', 'ar': 'تعديل الملف الشخصي'},
    'symptoms': {'en': 'Symptoms', 'fr': 'Symptômes', 'sw': 'Dalili', 'ar': 'الأعراض'},
    'report_symptoms': {'en': 'Report symptoms', 'fr': 'Signaler des symptômes', 'sw': 'Ripoti dalili', 'ar': 'الإبلاغ عن الأعراض'},
    'consultation': {'en': 'Consultation', 'fr': 'Consultation', 'sw': 'Ushauri', 'ar': 'استشارة'},
    'date_time': {'en': 'Date & time', 'fr': 'Date et heure', 'sw': 'Tarehe na wakati', 'ar': 'التاريخ والوقت'},
    'notes': {'en': 'Notes', 'fr': 'Remarques', 'sw': 'Maelezo', 'ar': 'ملاحظات'},
    'doctor': {'en': 'Doctor', 'fr': 'Médecin', 'sw': 'Daktari', 'ar': 'طبيب'},
    'clinic': {'en': 'Clinic', 'fr': 'Clinique', 'sw': 'Kliniki', 'ar': 'عيادة'},
    'status': {'en': 'Status', 'fr': 'Statut', 'sw': 'Hali', 'ar': 'الحالة'},
    'upcoming': {'en': 'Upcoming', 'fr': 'À venir', 'sw': 'Ijayo', 'ar': 'قادم'},
    'completed': {'en': 'Completed', 'fr': 'Terminé', 'sw': 'Imekamilika', 'ar': 'مكتمل'},
    'cancelled': {'en': 'Cancelled', 'fr': 'Annulé', 'sw': 'Imeghairiwa', 'ar': 'ملغى'},
    'normal': {'en': 'Normal', 'fr': 'Normal', 'sw': 'Kawaida', 'ar': 'طبيعي'},
    'flagged': {'en': 'Flagged', 'fr': 'Signalé', 'sw': 'Imebainishwa', 'ar': 'محدد'},
    'home': {'en': 'Home', 'fr': 'Accueil', 'sw': 'Nyumbani', 'ar': 'الرئيسية'},
    'get_started': {'en': 'Get Started', 'fr': 'Commencer', 'sw': 'Anza', 'ar': 'ابدأ'},
    'language': {'en': 'Language', 'fr': 'Langue', 'sw': 'Lugha', 'ar': 'اللغة'},
    'family_contact': {'en': 'Family contact', 'fr': 'Contact familial', 'sw': 'Mawasiliano ya familia', 'ar': 'جهة اتصال العائلة'},

    'login_heading': {'en': 'Log in to your account', 'fr': 'Connectez-vous à votre compte', 'sw': 'Ingia kwenye akaunti yako', 'ar': 'سجّل الدخول إلى حسابك'},
    'register_heading': {'en': 'Create your account', 'fr': 'Créez votre compte', 'sw': 'Fungua akaunti yako', 'ar': 'أنشئ حسابك'},
    'no_account': {'en': "Don't have an account?", 'fr': "Vous n'avez pas de compte ?", 'sw': 'Huna akaunti?', 'ar': 'ليس لديك حساب؟'},
    'have_account': {'en': 'Already have an account?', 'fr': 'Vous avez déjà un compte ?', 'sw': 'Una akaunti tayari?', 'ar': 'هل لديك حساب بالفعل؟'},
    'register_here': {'en': 'Register here', 'fr': "S'inscrire ici", 'sw': 'Jisajili hapa', 'ar': 'سجّل هنا'},
    'log_in_link': {'en': 'Log in', 'fr': 'Connexion', 'sw': 'Ingia', 'ar': 'تسجيل الدخول'},
    'welcome_back': {'en': 'Welcome back', 'fr': 'Content de vous revoir', 'sw': 'Karibu tena', 'ar': 'مرحباً بعودتك'},
    'care_today': {'en': "Here's what's happening with your care today.", 'fr': "Voici ce qui se passe avec vos soins aujourd'hui.", 'sw': 'Haya ndiyo yanayoendelea na huduma yako ya afya leo.', 'ar': 'إليك آخر مستجدات رعايتك الصحية اليوم.'},
    'upcoming_appointments': {'en': 'Upcoming appointments', 'fr': 'Rendez-vous à venir', 'sw': 'Miadi ijayo', 'ar': 'المواعيد القادمة'},
    'active_consultations': {'en': 'Active consultations', 'fr': 'Consultations en cours', 'sw': 'Ushauri unaoendelea', 'ar': 'الاستشارات النشطة'},
    'your_appointments': {'en': 'Your appointments', 'fr': 'Vos rendez-vous', 'sw': 'Miadi yako', 'ar': 'مواعيدك'},
    'book_appointment_desc': {'en': 'Schedule with a provider', 'fr': 'Planifier avec un professionnel', 'sw': 'Panga na mtoa huduma', 'ar': 'حدد موعدًا مع مقدم رعاية'},
    'report_symptoms_desc': {'en': 'Get matched to a provider', 'fr': 'Soyez mis en relation avec un professionnel', 'sw': 'Utaunganishwa na mtoa huduma', 'ar': 'سيتم ربطك بمقدم رعاية'},
    'medical_records_desc': {'en': 'View your health history', 'fr': 'Consultez votre historique de santé', 'sw': 'Angalia historia yako ya afya', 'ar': 'اطّلع على سجلك الصحي'},
    'health_education_desc': {'en': 'Learn in your language', 'fr': 'Apprenez dans votre langue', 'sw': 'Jifunze kwa lugha yako', 'ar': 'تعلّم بلغتك'},
    'emergency_desc': {'en': 'Notify nearby providers now', 'fr': 'Alertez les professionnels à proximité', 'sw': 'Arifu watoa huduma walio karibu sasa', 'ar': 'أبلغ مقدمي الرعاية القريبين الآن'},
    'meet_providers': {'en': 'Meet our healthcare providers', 'fr': 'Découvrez nos professionnels de santé', 'sw': 'Kutana na watoa huduma wetu wa afya', 'ar': 'تعرّف على مقدمي الرعاية الصحية لدينا'},
    'pharmacy_team': {'en': 'Pharmacy team', 'fr': 'Équipe pharmacie', 'sw': 'Timu ya famasi', 'ar': 'فريق الصيدلية'},
    'nursing_team': {'en': 'Nursing team', 'fr': 'Équipe infirmière', 'sw': 'Timu ya wauguzi', 'ar': 'فريق التمريض'},
    'pediatric_team': {'en': 'Pediatric team', 'fr': 'Équipe pédiatrique', 'sw': 'Timu ya watoto', 'ar': 'فريق طب الأطفال'},
    'consultation_team': {'en': 'Consultation team', 'fr': 'Équipe de consultation', 'sw': 'Timu ya ushauri', 'ar': 'فريق الاستشارات'},
    'care_team_generic': {'en': 'Care team', 'fr': 'Équipe de soins', 'sw': 'Timu ya huduma', 'ar': 'فريق الرعاية'},
    'team_word': {'en': 'team', 'fr': 'équipe', 'sw': 'timu', 'ar': 'فريق'},
    'members_label': {'en': 'members', 'fr': 'membres', 'sw': 'wanachama', 'ar': 'أعضاء'},
    'member_label': {'en': 'member', 'fr': 'membre', 'sw': 'mwanachama', 'ar': 'عضو'},
    'verified_providers_title': {'en': 'Verified healthcare providers', 'fr': 'Professionnels de santé vérifiés', 'sw': 'Watoa huduma waliothibitishwa', 'ar': 'مقدمو الرعاية الصحية المعتمدون'},
    'no_verified_providers': {'en': 'No verified providers yet — check back soon.', 'fr': "Aucun professionnel vérifié pour l'instant — revenez bientôt.", 'sw': 'Hakuna watoa huduma waliothibitishwa bado — rudi tena hivi karibuni.', 'ar': 'لا يوجد مقدمو رعاية معتمدون بعد — تحقق لاحقًا.'},
    'could_not_reach_server': {'en': 'Could not reach the server.', 'fr': 'Impossible de joindre le serveur.', 'sw': 'Imeshindwa kufikia seva.', 'ar': 'تعذر الوصول إلى الخادم.'},
    'save_changes': {'en': 'Save changes', 'fr': 'Enregistrer les modifications', 'sw': 'Hifadhi mabadiliko', 'ar': 'حفظ التغييرات'},
    'family_contact_optional': {'en': 'Family contact phone (optional)', 'fr': 'Téléphone du contact familial (facultatif)', 'sw': 'Simu ya mawasiliano ya familia (hiari)', 'ar': 'هاتف جهة اتصال العائلة (اختياري)'},
    'download_offline': {'en': 'Download for offline', 'fr': 'Télécharger pour usage hors ligne', 'sw': 'Pakua kwa matumizi nje ya mtandao', 'ar': 'تنزيل للاستخدام دون اتصال'},
    'health_ed_heading': {'en': 'Health education library', 'fr': 'Bibliothèque d’éducation à la santé', 'sw': 'Maktaba ya elimu ya afya', 'ar': 'مكتبة التثقيف الصحي'},
    'symptom_report_heading': {'en': 'Report your symptoms', 'fr': 'Signalez vos symptômes', 'sw': 'Ripoti dalili zako', 'ar': 'أبلغ عن أعراضك'},
    'symptom_report_desc': {'en': "Choose everything that applies, and add anything else in your own words. A verified healthcare provider will be assigned to your case automatically.", 'fr': "Sélectionnez tout ce qui s'applique et ajoutez toute autre précision dans vos propres mots. Un professionnel de santé vérifié sera automatiquement assigné à votre dossier.", 'sw': 'Chagua kila kinachohusika, kisha ongeza maelezo mengine kwa maneno yako. Mtoa huduma aliyethibitishwa atapangiwa kesi yako moja kwa moja.', 'ar': 'اختر كل ما ينطبق، وأضف أي تفاصيل أخرى بكلماتك. سيتم تعيين مقدم رعاية موثّق لحالتك تلقائيًا.'},
    'your_consultations': {'en': 'Your consultations', 'fr': 'Vos consultations', 'sw': 'Ushauri wako', 'ar': 'استشاراتك'},
    'describe_own_words': {'en': 'Describe in your own words (optional)', 'fr': 'Décrivez avec vos propres mots (facultatif)', 'sw': 'Eleza kwa maneno yako (hiari)', 'ar': 'صف الأمر بكلماتك (اختياري)'},
    'submit_report': {'en': 'Submit report', 'fr': 'Envoyer le rapport', 'sw': 'Wasilisha ripoti', 'ar': 'إرسال التقرير'},
    'cancel_and_back': {'en': 'Cancel and go back', 'fr': 'Annuler et revenir', 'sw': 'Ghairi na urudi', 'ar': 'إلغاء والعودة'},
    'title_field': {'en': 'Title', 'fr': 'Titre', 'sw': 'Kichwa', 'ar': 'العنوان'},
    'details_optional': {'en': 'Details (optional)', 'fr': 'Détails (facultatif)', 'sw': 'Maelezo (hiari)', 'ar': 'التفاصيل (اختياري)'},
    'date_recorded': {'en': 'Date recorded', 'fr': "Date d'enregistrement", 'sw': 'Tarehe ya kurekodiwa', 'ar': 'تاريخ التسجيل'},
    'provider_field': {'en': 'Provider', 'fr': 'Professionnel de santé', 'sw': 'Mtoa huduma', 'ar': 'مقدم الرعاية'},
    'save_record': {'en': 'Save record', 'fr': 'Enregistrer le dossier', 'sw': 'Hifadhi rekodi', 'ar': 'حفظ السجل'},
    'book_appointment_btn': {'en': 'Book appointment', 'fr': 'Prendre rendez-vous', 'sw': 'Weka miadi', 'ar': 'حجز موعد'},
    'book_appointment_heading': {'en': 'Book an appointment', 'fr': 'Prendre un rendez-vous', 'sw': 'Weka miadi', 'ar': 'حجز موعد'},
    'add_record_heading': {'en': 'Add a medical record', 'fr': 'Ajouter un dossier médical', 'sw': 'Ongeza rekodi ya afya', 'ar': 'إضافة سجل طبي'},

    'tagline': {'en': 'Healthcare made easy, anywhere', 'fr': 'Les soins de santé simplifiés, partout', 'sw': 'Huduma ya afya iliyorahisishwa, popote', 'ar': 'رعاية صحية سهلة، في أي مكان'},
    'hero_lede': {'en': 'Connect with verified healthcare providers, report symptoms, book appointments, and trigger emergency alerts — over the internet or plain SMS, no smartphone required.', 'fr': "Contactez des professionnels de santé vérifiés, signalez vos symptômes, prenez rendez-vous et déclenchez des alertes d'urgence — via Internet ou simple SMS, sans smartphone requis.", 'sw': 'Wasiliana na watoa huduma za afya waliothibitishwa, ripoti dalili, weka miadi, na tuma tahadhari za dharura — kupitia intaneti au SMS ya kawaida, hakuna simu janja inayohitajika.', 'ar': 'تواصل مع مقدمي رعاية صحية موثّقين، أبلغ عن الأعراض، احجز المواعيد، وأطلق تنبيهات الطوارئ — عبر الإنترنت أو الرسائل النصية القصيرة فقط، دون الحاجة لهاتف ذكي.'},
    'bullet_sms': {'en': 'SMS & mobile access, even offline', 'fr': 'Accès SMS et mobile, même hors ligne', 'sw': 'Ufikiaji wa SMS na simu, hata bila mtandao', 'ar': 'وصول عبر الرسائل النصية والجوال، حتى بلا اتصال'},
    'bullet_providers': {'en': 'Qualified, verified healthcare providers', 'fr': 'Professionnels de santé qualifiés et vérifiés', 'sw': 'Watoa huduma waliohitimu na kuthibitishwa', 'ar': 'مقدمو رعاية صحية مؤهلون وموثّقون'},
    'bullet_emergency': {'en': 'One-tap emergency alerts', 'fr': "Alertes d'urgence en un clic", 'sw': 'Tahadhari za dharura kwa mguso mmoja', 'ar': 'تنبيهات طوارئ بلمسة واحدة'},
    'bullet_communities': {'en': 'Built for low-resource African communities', 'fr': 'Conçu pour les communautés africaines à faibles ressources', 'sw': 'Imeundwa kwa jamii za Kiafrika zenye rasilimali chache', 'ar': 'مصمم للمجتمعات الأفريقية محدودة الموارد'},
    'hero_headline_prefix': {'en': 'Quality care for every', 'fr': 'Des soins de qualité pour chaque', 'sw': 'Huduma bora kwa kila', 'ar': 'رعاية جيدة لكل'},
    'hero_headline_accent': {'en': 'African community.', 'fr': 'communauté africaine.', 'sw': 'jamii ya Kiafrika.', 'ar': 'مجتمع أفريقي.'},
    'role_provider': {'en': 'Healthcare provider', 'fr': 'Professionnel de santé', 'sw': 'Mtoa huduma wa afya', 'ar': 'مقدم رعاية صحية'},
    'role_volunteer': {'en': 'Community volunteer', 'fr': 'Bénévole communautaire', 'sw': 'Kujitolea kwa jamii', 'ar': 'متطوع مجتمعي'},
    'role_admin': {'en': 'Administrator', 'fr': 'Administrateur', 'sw': 'Msimamizi', 'ar': 'المسؤول'},

    'symptom_fever': {'en': 'Fever', 'fr': 'Fièvre', 'sw': 'Homa', 'ar': 'حمى'},
    'symptom_cough': {'en': 'Cough', 'fr': 'Toux', 'sw': 'Kikohozi', 'ar': 'سعال'},
    'symptom_headache': {'en': 'Headache', 'fr': 'Mal de tête', 'sw': 'Maumivu ya kichwa', 'ar': 'صداع'},
    'symptom_diarrhea': {'en': 'Diarrhea', 'fr': 'Diarrhée', 'sw': 'Kuhara', 'ar': 'إسهال'},
    'symptom_vomiting': {'en': 'Vomiting', 'fr': 'Vomissements', 'sw': 'Kutapika', 'ar': 'قيء'},
    'symptom_bodyaches': {'en': 'Body aches', 'fr': 'Douleurs corporelles', 'sw': 'Maumivu ya mwili', 'ar': 'آلام في الجسم'},
    'symptom_breathing': {'en': 'Difficulty breathing', 'fr': 'Difficulté à respirer', 'sw': 'Ugumu wa kupumua', 'ar': 'صعوبة في التنفس'},
    'symptom_rash': {'en': 'Rash', 'fr': 'Éruption cutanée', 'sw': 'Upele', 'ar': 'طفح جلدي'},
    'symptom_bleeding': {'en': 'Bleeding', 'fr': 'Saignement', 'sw': 'Kutokwa na damu', 'ar': 'نزيف'},
    'symptom_fatigue': {'en': 'Fatigue', 'fr': 'Fatigue', 'sw': 'Uchovu', 'ar': 'إرهاق'},

    'provider_login_heading': {'en': 'Provider login', 'fr': 'Connexion professionnel de santé', 'sw': 'Kuingia kwa mtoa huduma', 'ar': 'تسجيل دخول مقدم الرعاية'},
    'admin_login_heading': {'en': 'Administrator login', 'fr': 'Connexion administrateur', 'sw': 'Kuingia kwa msimamizi', 'ar': 'تسجيل دخول المسؤول'},
    'volunteer_login_heading': {'en': 'Volunteer login', 'fr': 'Connexion bénévole', 'sw': 'Kuingia kwa mjitolea', 'ar': 'تسجيل دخول المتطوع'},
    'not_registered_yet': {'en': 'Not registered yet?', 'fr': 'Pas encore inscrit ?', 'sw': 'Bado hujajisajili?', 'ar': 'لم تسجّل بعد؟'},
    'consultation_queue_heading': {'en': 'Your consultation queue', 'fr': 'Votre file de consultations', 'sw': 'Foleni yako ya ushauri', 'ar': 'قائمة استشاراتك'},
    'respond_to_consultation_heading': {'en': 'Respond to consultation', 'fr': 'Répondre à la consultation', 'sw': 'Jibu ushauri', 'ar': 'الرد على الاستشارة'},
    'response_notes_label': {'en': 'Response notes', 'fr': 'Notes de réponse', 'sw': 'Maelezo ya jibu', 'ar': 'ملاحظات الرد'},
    'escalate_critical_label': {'en': 'Escalate as critical (creates an emergency alert)', 'fr': "Escalader en urgence (crée une alerte d'urgence)", 'sw': 'Panda hadhi kuwa dharura (huunda tahadhari ya dharura)', 'ar': 'تصعيد كحرِج (ينشئ تنبيه طوارئ)'},
    'close_case_label': {'en': 'Close this case', 'fr': 'Clôturer ce dossier', 'sw': 'Funga kesi hii', 'ar': 'إغلاق هذه الحالة'},
    'save_response_btn': {'en': 'Save response', 'fr': 'Enregistrer la réponse', 'sw': 'Hifadhi jibu', 'ar': 'حفظ الرد'},
    'mark_completed_btn': {'en': 'Mark completed', 'fr': 'Marquer comme terminé', 'sw': 'Weka alama imekamilika', 'ar': 'وضع علامة مكتمل'},
    'alerts_in_region_heading': {'en': 'Emergency alerts in your region', 'fr': "Alertes d'urgence dans votre région", 'sw': 'Tahadhari za dharura katika eneo lako', 'ar': 'تنبيهات الطوارئ في منطقتك'},
    'resolve_btn': {'en': 'Resolve', 'fr': 'Résoudre', 'sw': 'Tatua', 'ar': 'حل'},
    'respond_btn': {'en': 'Respond', 'fr': 'Répondre', 'sw': 'Jibu', 'ar': 'الرد'},
    'view_records_btn': {'en': 'View records', 'fr': 'Voir les dossiers', 'sw': 'Angalia rekodi', 'ar': 'عرض السجلات'},
    'healthcare_providers_heading': {'en': 'Healthcare providers', 'fr': 'Professionnels de santé', 'sw': 'Watoa huduma za afya', 'ar': 'مقدمو الرعاية الصحية'},
    'health_facilities_heading': {'en': 'Health facilities', 'fr': 'Établissements de santé', 'sw': 'Vituo vya afya', 'ar': 'المرافق الصحية'},
    'platform_reports_heading': {'en': 'Platform reports', 'fr': 'Rapports de la plateforme', 'sw': 'Ripoti za jukwaa', 'ar': 'تقارير المنصة'},
    'add_health_facility_heading': {'en': 'Add a health facility', 'fr': 'Ajouter un établissement de santé', 'sw': 'Ongeza kituo cha afya', 'ar': 'إضافة مرفق صحي'},
    'verify_btn': {'en': 'Verify', 'fr': 'Vérifier', 'sw': 'Thibitisha', 'ar': 'توثيق'},
    'suspend_btn': {'en': 'Suspend', 'fr': 'Suspendre', 'sw': 'Simamisha', 'ar': 'إيقاف'},
    'register_provider_heading': {'en': 'Register as a healthcare provider', 'fr': 'Inscrivez-vous en tant que professionnel de santé', 'sw': 'Jisajili kama mtoa huduma za afya', 'ar': 'سجّل كمقدم رعاية صحية'},
    'register_volunteer_heading': {'en': 'Register as a community health volunteer', 'fr': 'Inscrivez-vous en tant que bénévole de santé communautaire', 'sw': 'Jisajili kama mjitolea wa afya wa jamii', 'ar': 'سجّل كمتطوع صحي مجتمعي'},
    'specialization_label': {'en': 'Specialization', 'fr': 'Spécialisation', 'sw': 'Utaalamu', 'ar': 'التخصص'},
    'assigned_region_label': {'en': 'Assigned region', 'fr': 'Région assignée', 'sw': 'Mkoa uliopangiwa', 'ar': 'المنطقة المخصصة'},
    'submit_consultation_heading': {'en': 'Submit a consultation for a patient', 'fr': 'Soumettre une consultation pour un patient', 'sw': 'Wasilisha ushauri kwa mgonjwa', 'ar': 'إرسال استشارة لمريض'},
    'trigger_alert_heading': {'en': 'Trigger an emergency alert for a patient', 'fr': "Déclencher une alerte d'urgence pour un patient", 'sw': 'Anzisha tahadhari ya dharura kwa mgonjwa', 'ar': 'إطلاق تنبيه طوارئ لمريض'},
    'patient_phone_label': {'en': 'Patient phone number', 'fr': 'Numéro de téléphone du patient', 'sw': 'Nambari ya simu ya mgonjwa', 'ar': 'رقم هاتف المريض'},
    'location_label': {'en': 'Location', 'fr': 'Emplacement', 'sw': 'Mahali', 'ar': 'الموقع'},
    'condition_label': {'en': 'Condition', 'fr': 'État', 'sw': 'Hali', 'ar': 'الحالة'},
    'consultations_nav': {'en': 'Consultations', 'fr': 'Consultations', 'sw': 'Ushauri', 'ar': 'الاستشارات'},
    'emergency_alerts_nav': {'en': 'Emergency Alerts', 'fr': "Alertes d'urgence", 'sw': 'Tahadhari za Dharura', 'ar': 'تنبيهات الطوارئ'},
    'admin_provisioned_note': {'en': 'Administrator accounts are provisioned by the platform team — there is no self-registration.', 'fr': "Les comptes administrateur sont créés par l'équipe de la plateforme — il n'y a pas d'auto-inscription.", 'sw': 'Akaunti za msimamizi hutolewa na timu ya jukwaa — hakuna kujisajili binafsi.', 'ar': 'يتم إنشاء حسابات المسؤولين من قبل فريق المنصة — لا يوجد تسجيل ذاتي.'},
    'provider_verify_note': {'en': 'Your account will need to be verified by an administrator before you can log in.', 'fr': 'Votre compte devra être vérifié par un administrateur avant que vous puissiez vous connecter.', 'sw': 'Akaunti yako itahitaji kuthibitishwa na msimamizi kabla ya kuingia.', 'ar': 'سيحتاج حسابك إلى توثيق من قِبل مسؤول قبل أن تتمكن من تسجيل الدخول.'},
    'already_verified': {'en': 'Already verified?', 'fr': 'Déjà vérifié ?', 'sw': 'Tayari umethibitishwa?', 'ar': 'تم التوثيق بالفعل؟'},
    'agree_to_provider_terms': {'en': 'I agree to the', 'fr': "J'accepte les", 'sw': 'Nakubali', 'ar': 'أوافق على'},
    'provider_terms_heading': {'en': 'Provider Terms & Conditions', 'fr': 'Conditions générales du professionnel de santé', 'sw': 'Masharti na Vigezo vya Mtoa Huduma', 'ar': 'شروط وأحكام مقدم الرعاية'},
    'volunteer_terms_heading': {'en': 'Volunteer Terms & Conditions', 'fr': 'Conditions générales du bénévole', 'sw': 'Masharti na Vigezo vya Mjitolea', 'ar': 'شروط وأحكام المتطوع'},
    'close_btn': {'en': 'Close', 'fr': 'Fermer', 'sw': 'Funga', 'ar': 'إغلاق'},
    'i_accept_btn': {'en': 'I Accept', 'fr': "J'accepte", 'sw': 'Nakubali', 'ar': 'أوافق'},
    'already_registered': {'en': 'Already registered?', 'fr': 'Déjà inscrit ?', 'sw': 'Tayari umejisajili?', 'ar': 'مسجّل بالفعل؟'},
    'agree_to_volunteer_terms': {'en': 'I agree to the', 'fr': "J'accepte les", 'sw': 'Nakubali', 'ar': 'أوافق على'},
    'no_consultations_yet': {'en': 'No consultations assigned yet.', 'fr': "Aucune consultation assignée pour l'instant.", 'sw': 'Hakuna ushauri uliopangiwa bado.', 'ar': 'لا توجد استشارات مُسندة بعد.'},
    'patient_label': {'en': 'Patient', 'fr': 'Patient', 'sw': 'Mgonjwa', 'ar': 'مريض'},
    'patient_records_title': {'en': 'Patient records', 'fr': 'Dossiers du patient', 'sw': 'Rekodi za mgonjwa', 'ar': 'سجلات المريض'},
    'could_not_load_records': {'en': 'Could not load records.', 'fr': 'Impossible de charger les dossiers.', 'sw': 'Imeshindwa kupakia rekodi.', 'ar': 'تعذر تحميل السجلات.'},
    'no_records_on_file': {'en': 'No records on file for this patient yet.', 'fr': "Aucun dossier enregistré pour ce patient pour l'instant.", 'sw': 'Hakuna rekodi za mgonjwa huyu bado.', 'ar': 'لا توجد سجلات لهذا المريض بعد.'},
    'records_heading_prefix': {'en': 'Records —', 'fr': 'Dossiers —', 'sw': 'Rekodi —', 'ar': 'السجلات —'},
    'no_appointments_yet': {'en': 'No appointments booked yet.', 'fr': "Aucun rendez-vous pris pour l'instant.", 'sw': 'Hakuna miadi iliyowekwa bado.', 'ar': 'لا توجد مواعيد محجوزة بعد.'},
    'no_alerts_in_region': {'en': 'No emergency alerts in your region.', 'fr': "Aucune alerte d'urgence dans votre région.", 'sw': 'Hakuna tahadhari za dharura katika eneo lako.', 'ar': 'لا توجد تنبيهات طوارئ في منطقتك.'},
    'verify_providers_note': {'en': 'Verify new providers before they can accept consultations, or suspend an existing one.', 'fr': "Vérifiez les nouveaux professionnels de santé avant qu'ils puissent accepter des consultations, ou suspendez-en un existant.", 'sw': 'Thibitisha watoa huduma wapya kabla ya kukubali ushauri, au simamisha aliyepo.', 'ar': 'وثّق مقدمي الرعاية الجدد قبل أن يتمكنوا من قبول الاستشارات، أو أوقف مقدمًا حاليًا.'},
    'add_facility_btn': {'en': '+ Add facility', 'fr': '+ Ajouter un établissement', 'sw': '+ Ongeza kituo', 'ar': '+ إضافة مرفق'},
    'facilities_note': {'en': 'Clinics, hospitals, and pharmacies patients can select when booking an appointment.', 'fr': 'Cliniques, hôpitaux et pharmacies que les patients peuvent choisir lors de la prise de rendez-vous.', 'sw': 'Kliniki, hospitali, na maduka ya dawa wagonjwa wanaweza kuchagua wanapoweka miadi.', 'ar': 'العيادات والمستشفيات والصيدليات التي يمكن للمرضى اختيارها عند حجز موعد.'},
    'facility_name_label': {'en': 'Name', 'fr': 'Nom', 'sw': 'Jina', 'ar': 'الاسم'},
    'facility_type_label': {'en': 'Type', 'fr': 'Type', 'sw': 'Aina', 'ar': 'النوع'},
    'facility_type_clinic': {'en': 'Clinic', 'fr': 'Clinique', 'sw': 'Kliniki', 'ar': 'عيادة'},
    'facility_type_hospital': {'en': 'Hospital', 'fr': 'Hôpital', 'sw': 'Hospitali', 'ar': 'مستشفى'},
    'facility_type_pharmacy': {'en': 'Pharmacy', 'fr': 'Pharmacie', 'sw': 'Duka la dawa', 'ar': 'صيدلية'},
    'phone_number_optional': {'en': 'Phone number (optional)', 'fr': 'Numéro de téléphone (facultatif)', 'sw': 'Nambari ya simu (hiari)', 'ar': 'رقم الهاتف (اختياري)'},
    'add_facility_submit': {'en': 'Add facility', 'fr': 'Ajouter l’établissement', 'sw': 'Ongeza kituo', 'ar': 'إضافة المرفق'},
    'no_providers_registered': {'en': 'No providers registered yet.', 'fr': "Aucun professionnel inscrit pour l'instant.", 'sw': 'Hakuna watoa huduma waliosajiliwa bado.', 'ar': 'لا يوجد مقدمو رعاية مسجلون بعد.'},
    'verified_status': {'en': 'verified', 'fr': 'vérifié', 'sw': 'imethibitishwa', 'ar': 'موثّق'},
    'pending_status': {'en': 'pending', 'fr': 'en attente', 'sw': 'inasubiri', 'ar': 'قيد الانتظار'},
    'remove_btn': {'en': 'Remove', 'fr': 'Supprimer', 'sw': 'Ondoa', 'ar': 'إزالة'},
    'no_facilities_yet': {'en': 'No facilities added yet.', 'fr': "Aucun établissement ajouté pour l'instant.", 'sw': 'Hakuna vituo vilivyoongezwa bado.', 'ar': 'لم تتم إضافة أي مرفق بعد.'},
    'verified_providers_report_label': {'en': 'Verified providers', 'fr': 'Professionnels vérifiés', 'sw': 'Watoa huduma waliothibitishwa', 'ar': 'مقدمو الرعاية الموثّقون'},
    'pending_report_label': {'en': 'Pending', 'fr': 'En attente', 'sw': 'Inasubiri', 'ar': 'قيد الانتظار'},
    'patients_by_country_label': {'en': 'Patients by country', 'fr': 'Patients par pays', 'sw': 'Wagonjwa kwa nchi', 'ar': 'المرضى حسب الدولة'},
    'providers_by_region_label': {'en': 'Providers by region', 'fr': 'Professionnels par région', 'sw': 'Watoa huduma kwa mkoa', 'ar': 'مقدمو الرعاية حسب المنطقة'},
    'consultations_by_status_label': {'en': 'Consultations by status', 'fr': 'Consultations par statut', 'sw': 'Ushauri kwa hali', 'ar': 'الاستشارات حسب الحالة'},
    'alerts_by_status_label': {'en': 'Emergency alerts by status', 'fr': "Alertes d'urgence par statut", 'sw': 'Tahadhari za dharura kwa hali', 'ar': 'تنبيهات الطوارئ حسب الحالة'},
    'no_data_yet': {'en': 'No data yet.', 'fr': "Pas encore de données.", 'sw': 'Hakuna data bado.', 'ar': 'لا توجد بيانات بعد.'},
    'volunteer_patient_registered_note': {'en': 'The patient must already be registered on Umoja Health Connect.', 'fr': 'Le patient doit déjà être inscrit sur Umoja Health Connect.', 'sw': 'Mgonjwa lazima awe tayari amesajiliwa kwenye Umoja Health Connect.', 'ar': 'يجب أن يكون المريض مسجلاً بالفعل في Umoja Health Connect.'},
    'submit_consultation_btn': {'en': 'Submit consultation', 'fr': 'Soumettre la consultation', 'sw': 'Wasilisha ushauri', 'ar': 'إرسال الاستشارة'},
    'send_emergency_alert_btn': {'en': 'Send emergency alert', 'fr': "Envoyer l'alerte d'urgence", 'sw': 'Tuma tahadhari ya dharura', 'ar': 'إرسال تنبيه الطوارئ'},
    'no_consultations_submitted': {'en': 'No consultations submitted yet.', 'fr': "Aucune consultation soumise pour l'instant.", 'sw': 'Hakuna ushauri uliowasilishwa bado.', 'ar': 'لم يتم إرسال أي استشارة بعد.'},
    'no_alerts_triggered': {'en': 'No emergency alerts triggered yet.', 'fr': "Aucune alerte d'urgence déclenchée pour l'instant.", 'sw': 'Hakuna tahadhari za dharura zilizoanzishwa bado.', 'ar': 'لم يتم إطلاق أي تنبيه طوارئ بعد.'},
}


def labels_for(lang):
    lang = lang if lang in LANGUAGES else 'en'
    return {
        'language': lang,
        'dir': 'rtl' if lang in RTL_LANGUAGES else 'ltr',
        'labels': {key: values.get(lang, values['en']) for key, values in LABELS.items()},
    }
